[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/b24proxy"
  to = "/.netlify/functions/b24proxy"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
